#!/usr/bin/env python3
"""Losslessly pack a 480x320 RGB111 byte image (or legacy C header) as RLE16.

Each 16-bit word stores a nonzero run length in bits 15:3 and RGB in bits 2:0.
The LCD consumes runs directly; no full-size decompression buffer is needed.
"""
import argparse
import hashlib
from itertools import groupby
from pathlib import Path
import re

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('input', type=Path)
parser.add_argument('output', type=Path)
args = parser.parse_args()
if args.input.suffix == '.h':
    body = args.input.read_text().split('{', 1)[1].split('}', 1)[0]
    pixels = bytes(map(int, re.findall(r'\b\d+\b', body)))
else:
    pixels = args.input.read_bytes()
if len(pixels) != 480 * 320 or any(c > 7 for c in pixels):
    parser.error('input must contain exactly 480*320 RGB111 pixels (0..7)')
runs = []
for color, group in groupby(pixels):
    remaining = sum(1 for _ in group)
    while remaining:
        count = min(remaining, 8191)
        runs.append((count << 3) | color)
        remaining -= count
decoded = bytes(color for word in runs for color in [word & 7] * (word >> 3))
assert decoded == pixels
lines = [
    '#ifndef PSC_BOOT_LOGO_H', '#define PSC_BOOT_LOGO_H', '',
    '/* PSC-ONE boot logo: 480x320 RGB111, lossless RLE16.',
    ' * Generated by tools/pack_boot_logo.py; bits 15:3 = count, 2:0 = RGB.',
    ' * Decoded SHA-256: ' + hashlib.sha256(pixels).hexdigest(),
    ' */', 'static const unsigned short boot_logo_rle[] = {']
for i in range(0, len(runs), 12):
    lines.append('    ' + ', '.join(f'0x{word:04x}' for word in runs[i:i+12]) + ',')
lines += ['};', '', '#endif', '']
args.output.write_text('\n'.join(lines))
print(f'{len(pixels)} -> {len(runs) * 2} bytes; all pixels identical')
